import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3500,
            style: {
              background: "#ffffff",
              border: "2px solid #10233a",
              borderRadius: "20px",
              boxShadow: "0 18px 42px rgba(16, 35, 58, 0.18)",
              color: "#10233a",
              padding: "14px 16px",
            },
            loading: {
              duration: Infinity,
              style: {
                background: "#16324f",
                color: "#ffffff",
                border: "2px solid #0b1827",
              },
              iconTheme: {
                primary: "#f7b32b",
                secondary: "#16324f",
              },
            },
            success: {
              style: {
                background: "#19a974",
                color: "#ffffff",
                border: "2px solid #0d6b48",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#19a974",
              },
            },
            error: {
              style: {
                background: "#ff6b57",
                color: "#ffffff",
                border: "2px solid #cb4b3a",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#ff6b57",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
